"""Add topics and questions

Revision ID: 940b1a54a2d2
Revises: 89f471ff1df2
Create Date: 2024-05-06 18:22:28.276839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940b1a54a2d2'
down_revision: Union[str, None] = '89f471ff1df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
