"""add duration & description in sobes_questions

Revision ID: 0b4e11f11dfe
Revises: 7375f6f0b3d2
Create Date: 2024-06-18 19:49:04.189154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4e11f11dfe'
down_revision: Union[str, None] = '7375f6f0b3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sobes_questions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('sobes_questions', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sobes_questions', 'duration')
    op.drop_column('sobes_questions', 'description')
    # ### end Alembic commands ###
