"""Add SobesModel & SobesQuestionModel

Revision ID: 3a4a4380689b
Revises: e0ed44896a26
Create Date: 2024-06-16 23:40:14.975551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4a4380689b'
down_revision: Union[str, None] = 'e0ed44896a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
